### ISSUE TITLE
pl.path requires LuaFileSystem error

### ISSUE THREAD

**Issue by linrongbin16** [notomo/vusted#17]
first thanks to your work so I could do unit test with lua on Neovim.

Here's a CI pipeline I want to do vusted unit tests on Windows, to support Neovim plugin running on Windows: https://github.com/linrongbin16/commons.nvim/pull/148

Here's the action runs: https://github.com/linrongbin16/commons.nvim/actions/runs/7382472681/job/20082321700

<img width="1697" alt="image" src="https://github.com/notomo/vusted/assets/6496887/7abd927a-08b0-41e0-8d8d-9a9986ac5208">

in the CI pipeline, I installed lua-5.1 and luarocks via the [hererocks](https://github.com/luarocks/hererocks), then install all the vusted dependencies, they all succeed, but vusted failed to run with error:

```
pre-vimrc command line..script D:\a\commons.nvim\commons.nvim\env\bin/vusted_entry.vim, line 20
Vim(lua):E5108: Error executing lua
...commons.nvim\commons.nvim\env\/share/lua/5.1/pl\path.lua:26: pl.path requires LuaFileSystem
stack traceback:        [C]: in function 'error'
...commons.nvim\commons.nvim\env\/share/lua/5.1/pl\path.lua:26: in main chunk        [C]: in function 'require'
...s.nvim\commons.nvim\env\/share/lua/5.1/busted\runner.lua:3: in main chunk        [C]: in function 'require'        
...mons.nvim\commons.nvim\env\/share/lua/5.1/vusted/run.lua:18: in function <...mons.nvim\commons.nvim\env\/share/lua/5.1/vusted/run.lua:1>        
[string ":lua"]:10: in main chunk
```

I'm not sure why that happened, would you please help on that?

**Comment by notomo** [comment]
Hi! This is LuaFileSystem's limitation.

> On Windows, the C runtime used to compile LuaFileSystem must be the same runtime that Lua uses, or some LuaFileSystem functions will not work.

https://lunarmodules.github.io/luafilesystem/manual.html#building

FYI: I use the following workaround.
https://github.com/notomo/action-setup-nvim-lua/blob/cc7bc230b4ed5c9cbb2df9570bb749f560b69001/src/luarocks.js#L57-L65

**Comment by linrongbin16** [comment]
hi @notomo , really thanks to your reply, I had updated my CI yaml file: https://github.com/linrongbin16/commons.nvim/pull/148/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR63-R85.

It's now:

```yml
  windows_unit_test:
    name: Windows Unit Test
    strategy:
      matrix:
        nvim_version: [stable, nightly, v0.6.0, v0.7.0]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          neovim: true
          version: ${{ matrix.nvim_version }}
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: notomo/action-setup-nvim-lua@v1
      - run: |
          luarocks install busted
          luarocks install vusted
          vusted --shuffle ./test
```

It does following steps:
1. checkout git repo source code, it's the plugin source code I will test.
2. setup 'nvim'.
3. setup MSVC (the `cl`) VC++ compiler.
4. use [action-setup-nvim-lua@v1](https://github.com/notomo/action-setup-nvim-lua) you mentioned above (I think it's going to install `luarocks` and `luajit-2`).
5. setup `busted` and `vusted`, then run the unit tests.

But there's 2 more errors in action runs: https://github.com/linrongbin16/commons.nvim/actions/runs/7383346276/job/20084404068

The Error-1: failed to install `luasystem` library.

<img width="1717" alt="image" src="https://github.com/notomo/vusted/assets/6496887/9fdda240-0508-4247-aea7-21aea839951f">

The Error-2: failed to find `vusted` executable.

<img width="1707" alt="image" src="https://github.com/notomo/vusted/assets/6496887/6c0f859b-6920-4682-b7f1-e3acd56ddbfd">

I guess the error rootcause is failed to install `luasystem`, would you please help me?
