### ISSUE TITLE
currentline is nil

### ISSUE THREAD

**Issue by glepnir** [notomo/vusted#8]
run `vusted tests` it works fine. all test case passed. run in github workflow I got this error

```
not ok 1 - 
...im/.luarocks/share/lua/5.1/busted/outputHandlers/TAP.lua:44: attempt to concatenate field 'currentline' (a nil value)
```

mine `ci.yml` is

```yml
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          neovim: true
          version: nightly

      - name: luajit
        uses: leafo/gh-actions-lua@v8
        with:
          luaVersion: "luajit-2.1.0-beta3"

      - name: luarocks
        uses: leafo/gh-actions-luarocks@v4

      - name: run test
        shell: bash
        run: |
          luarocks install luacheck
          luarocks install vusted
          vusted tests
```
